spring.application.name=confeitaria
server.error.include-message=always

# ORIGINAL POSTGRES DOCKER
spring.datasource.url=jdbc:postgresql://postgres:5432/confeitaria
spring.datasource.username=admin
spring.datasource.password=admin

# TEMP LOCAL H2
# spring.datasource.url=jdbc:h2:mem:confeitaria
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 CONSOLE
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

jwt.secret=sua-chave-secreta-com-pelo-menos-256-bits-aqui-mude-em-producao
jwt.expiration=86400000