spring.application.name=confeitaria
server.error.include-message=always
spring.profiles.active=prod

jwt.secret=sua-chave-secreta-com-pelo-menos-256-bits-aqui-mude-em-producao
jwt.expiration=5400000
jwt.refresh-expiration=604800000