# Banco de produção do Render (usado para dev até ter banco local)
spring.datasource.url=jdbc:postgresql://dpg-d7hcrvpkh4rs73abqe50-a.oregon-postgres.render.com:5432/confeitaria_oi3b
spring.datasource.username=confeitaria_oi3b_user
spring.datasource.password=c4gbIKVQzHkq5M2oSkak01qG2I4IP5TT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true